services:
  - type: web
    name: luminamart-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: MYSQLHOST
        sync: false
      - key: MYSQLPORT
        value: 3306
      - key: MYSQLDATABASE
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_CORS_ALLOWED_ORIGINS
        value: "https://luminamart-frontend-production.up.railway.app"

  - type: web
    name: luminamart-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://luminamart-backend-production.up.railway.app"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
