services:
  - type: web
    name: luminamart-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: MYSQLHOST
        value: mysql-acdf045-sanvara.l.aivencloud.com
      - key: MYSQLPORT
        value: 10406
      - key: MYSQLDATABASE
        value: defaultdb
      - key: MYSQLUSER
        value: avnadmin
      - key: MYSQLPASSWORD
        sync: false
      - key: MYSQL_SSL_MODE
        value: REQUIRED
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_CORS_ALLOWED_ORIGINS
        value: "https://luminamart-frontend.onrender.com,https://luminamart-frontend-production.up.railway.app"
      - key: APP_SEED_ENABLED
        value: true

  - type: web
    name: luminamart-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://luminamart-backend.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
